# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ts2ml',
                'doc_host': 'https://joaopcnogueira.github.io',
                'git_url': 'https://github.com/joaopcnogueira/ts2ml',
                'lib_path': 'ts2ml'},
  'syms': {'ts2ml.core': {'ts2ml.core.add_missing_slots': ('core.html#add_missing_slots', 'ts2ml/core.py')}}}
